### ISSUE TITLE
Shibboleth SP does not work

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxShibboleth#23]
OS: Ubuntu 14.04.2
Package: gluu-server-3.0.0_2-RC1~trusty+Ub14.04_amd64.deb

Tested Shibboleth SP with the following config: but instead of IDP login page, unsupported request page appeared.

![shib-tr](https://cloud.githubusercontent.com/assets/7703245/22629511/9d08b622-ec11-11e6-9742-347c699441d3.png)
---
![shib-tr-replying](https://cloud.githubusercontent.com/assets/7703245/22629514/9f0f0f3e-ec11-11e6-93e1-493dac5a8027.png)
When I accessed the protected link, I got the follwoing:
![shib-sp](https://cloud.githubusercontent.com/assets/7703245/22629518/aa4c517c-ec11-11e6-9f83-52ee9b87275f.png)
The `idp-process.log` contains the following:
```
2017-02-05 20:07:03,940 - INFO [org.opensaml.saml.common.binding.impl.SAMLMetadataLookupHandler:128] - Message Handler:  No metadata returned for https://shib.info/shibboleth in role {urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor with protocol urn:oasis:names:tc:SAML:2.0:protocol
2017-02-05 20:07:03,942 - WARN [net.shibboleth.idp.profile.impl.SelectProfileConfiguration:111] - Profile Action SelectProfileConfiguration: Profile http://shibboleth.net/ns/profiles/saml2/sso/browser is not available for relying party configuration shibboleth.UnverifiedRelyingParty
2017-02-05 20:07:03,943 - WARN [org.opensaml.profile.action.impl.LogEvent:76] - An error event occurred while processing the request: InvalidProfileConfiguration
```

**Comment by uboznikov** [comment]
@zamilskhan Is the metadata file also working with v2.4.4.2? It would be great to compare. Please also attach the metadata file. Thanks.

**Comment by jgworks** [comment]
I'm getting this in a brand new install of Gluu 3.0.0 on CentOS 7.3. Is there a workaround for this issue?

**Comment by zamilskhan** [comment]
@uboznikov The metadata file is attached here. The problem was not there in RC1 but it is there again. Tested in CentOS7.2.
The metadata is given below:
```
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="https://shib.info/shibboleth">
  <md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.1:protocol">
    <md:KeyDescriptor>
      <ds:KeyInfo>
        <ds:X509Data>
          <ds:X509Certificate>
MIIDdjCCAl4CCQCXsWeB+tNdbzANBgkqhkiG9w0BAQsFADB9MQswCQYDVQQGEwJV
UzELMAkGA1UECAwCVFgxDzANBgNVBAcMBkF1c3RpbjENMAsGA1UECgwER2x1dTEL
MAkGA1UECwwCUUExEjAQBgNVBAMMCXNoaWIuaW5mbzEgMB4GCSqGSIb3DQEJARYR
c3VwcG9ydEBzaGliLmluZm8wHhcNMTcwMTMwMTg1MzQ4WhcNMTgwMTMwMTg1MzQ4
WjB9MQswCQYDVQQGEwJVUzELMAkGA1UECAwCVFgxDzANBgNVBAcMBkF1c3RpbjEN
MAsGA1UECgwER2x1dTELMAkGA1UECwwCUUExEjAQBgNVBAMMCXNoaWIuaW5mbzEg
MB4GCSqGSIb3DQEJARYRc3VwcG9ydEBzaGliLmluZm8wggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDqY3+n2KX20EWgfENfvRa9Eb/j4zvBbr3HC7u0oSta
cuJ6njZmBcj3eBM3S9ZqPOWBSTcRst/S90T/b7HpTHKXMbgCvhY4xpiJp7L+TCzU
gCOZacZa9oNVAY7ET9QL1Ac57CJCvuZow1Hhaz1H8w3zB5Sc66wkgZSb7ABzdNXS
3acS8RPnRyfc9IK6c4hipBUzrWvko5mvPtGdWacjwJ0Sixr9fdhbas/7jkvse3yS
RnohOqyHTwH04TFoV8HE7OswOp7LTPFkiWZHiazuW4gKmbBd6mZ0hbsDSqhopHjR
NHf/1nCTcteKXsPgvg+9E6LGr6t68zycoZqm4nh7IEGVAgMBAAEwDQYJKoZIhvcN
AQELBQADggEBABhcnxTjuzHr5aCHgBiiL5OdGfVDVCnlkNmkllxzosmFuK3+IxKy
Xgvt14TPU3KP1B7nToNUtX9uFwV+6cCaNx/a7lGYca8gZLcI2B+IzqhKWJogTwGO
1doOqbm4WffAFJoPmgcR6cluaN+rQhi2/cHnTR6zb4iyREmZblxxvFTKCgQK9mtF
ZzBry7uCYnfoDZL5+5PbnXIPHzOeoNz4eZGr14MlvpTGnl0CAzUj1vTqDbebIfJl
8r4ssdN/Iqs239bwY8Z3wOZ+e2vOO1fnHcVeSSYiJt+3d82wkEkoziApBr2Voz2o
WUe12MvXoVvSk3JrEu8zbd39hgQDbx5scEc=
          </ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://shib.info/Shibboleth.sso/SAML2/POST" index="1"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="https://shib.info/Shibboleth.sso/SAML2/POST-SimpleSign" index="2"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:PAOS" Location="https://shib.info/Shibboleth.sso/SAML2/ECP" index="3"/>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:browser-post" Location="https://shib.info/Shibboleth.sso/SAML/POST" index="4"/>
  </md:SPSSODescriptor>
</md:EntityDescriptor>
```

**Comment by nynymike** [comment]
The entityID is `https://shib.info/shibboleth` are you sure this is correct? Also, can you attach the IDP metadata? IT may be a mismatch between the configured SP entityID and the actual IDP entityID>

**Comment by uboznikov** [comment]
@zamilskhan Thanks, please also attach the `shibboleth2.xml` file you used in the SP side.

**Comment by OneLoveAmaru** [comment]
We are having the same problem with a new install of 3.0.0 on CentOS 7.3 as well.

You can hit us here: https://sso.threattrack.net/idp/shibboleth

Here is our shibboleth2.xml: https://gist.github.com/OneLoveAmaru/5d6125403f0f14f49b85ae3c827bfd49

Anything else I can offer that'll help?

**Comment by zamilskhan** [comment]
Issue reproduced in CentOS 6.8. The idp process log shows the following warning
```
2017-02-08 20:11:14,645 - WARN [org.opensaml.profile.action.impl.LogEvent:76] - An error event occurred while processing the request: InvalidProfileCo
nfiguration
```
The idp metadata is as follows:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<EntityDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:shibmd="urn:mace:shibboleth:metadata:1.0" entityID="https://centos.gluu.info/idp/shibboleth">
<IDPSSODescriptor errorURL="https://centos.gluu.info/identity/feedback.htm" protocolSupportEnumeration="urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol">
<Extensions>
<shibmd:Scope regexp="false">centos.gluu.info</shibmd:Scope>
</Extensions>
<KeyDescriptor use="signing">
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIDZDCCAkwCCQDutw2an+lr5TANBgkqhkiG9w0BAQUFADB0MQswCQYDVQQGEwJ1 czELMAkGA1UECAwCdHgxDzANBgNVBAcMBmF1c3RpbjENMAsGA1UECgwEZ2x1dTEZ MBcGA1UEAwwQY2VudG9zLmdsdXUuaW5mbzEdMBsGCSqGSIb3DQEJARYObWFpbEBn bHV1LmluZm8wHhcNMTcwMjA4MTkyMzQ1WhcNMTgwMjA4MTkyMzQ1WjB0MQswCQYD VQQGEwJ1czELMAkGA1UECAwCdHgxDzANBgNVBAcMBmF1c3RpbjENMAsGA1UECgwE Z2x1dTEZMBcGA1UEAwwQY2VudG9zLmdsdXUuaW5mbzEdMBsGCSqGSIb3DQEJARYO bWFpbEBnbHV1LmluZm8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDi NnZge0/roIBjRmnMyQwH9r++1zqHuvdzX34JMCcJQYTOGrAM+GirPhHvck9w91C0 TSqFE6A8dwa1VzKCMYhxHJizCfXxDi3BHD+BjSCVJB9pq2uI6QHJLXZv9ZnvNVxP cwtxBrkubolyNE94yQJube81Nf7vRYVtazA03lPtdqxUdJeEZSNd716hQOl829JB DO+3BwjOBC5SdeZZ0W3tCNtbe1ovXUcj6dB9DdTNSr+I9QNNcsEw1oB+r9XaP82h hZ5fk2P2XCVb05A2kCdwqPNpvJAjmiwlYQpUVVEkBEOnl1qaJn0OE2HMXPjhd3rp MLO6qhroouNSQWVx7pUVAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAFqWgvMy9E/f L9X0sGwECVHcodc5LoYg75nmzRWDdR0YC3W6AOWWnoCZAG5VTox7Yyq6T4ypXUWv IuP3W9tUnrqbtBPlmmZ/USw1YEKNYA13dAhAWpdzoRBHFDiMc3aXuLah1fzRKqJ7 tnMSD29S1sflgOmOcaX8QYc5ftt8Yee9Sl6T9ZDjdpWc3d9zhXdASanvSg+yQnax XH+JRbwK2abFDEZAY67ldlUNnkJrwM+AhwAQXH43oZVjIgzhgfsq9htKOTBNaQEd nNtJ8EetDS07W4/fevLW5umEjNQSTw4dVLWn0S0l/tXTX4j+hroYdHO4tbPHL/hi FlN3bT9p8hQ=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</KeyDescriptor>
<KeyDescriptor use="encryption">
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIDZDCCAkwCCQCUtOCj931cKDANBgkqhkiG9w0BAQUFADB0MQswCQYDVQQGEwJ1 czELMAkGA1UECAwCdHgxDzANBgNVBAcMBmF1c3RpbjENMAsGA1UECgwEZ2x1dTEZ MBcGA1UEAwwQY2VudG9zLmdsdXUuaW5mbzEdMBsGCSqGSIb3DQEJARYObWFpbEBn bHV1LmluZm8wHhcNMTcwMjA4MTkyMzQ0WhcNMTgwMjA4MTkyMzQ0WjB0MQswCQYD VQQGEwJ1czELMAkGA1UECAwCdHgxDzANBgNVBAcMBmF1c3RpbjENMAsGA1UECgwE Z2x1dTEZMBcGA1UEAwwQY2VudG9zLmdsdXUuaW5mbzEdMBsGCSqGSIb3DQEJARYO bWFpbEBnbHV1LmluZm8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDL 9YcHcWXfKvNsPsFbxX88591Pn5gW65lgrSY3vN/gOA2y33yJkz9grZsIq/nirgzo J2SFjQilWCOpRr86mT5Z0VIPmMPEHGMwYqmcI1Pjs/M/D93wZExfjx4G30+awEwJ jn4IOevOap22+MS9OqElSpCi4XRuk6f/gJiIJTJZKyCIQxS7K+pEHJl7/fsOQHnA GiyVfJE0gEwXsALnnmNJn3ybu9Ut2Pr8IwKbdA6NqOyOKa8Nm8bEkwARnBxUulRu VcFC+eR4zE+twHNWHlSxizOZ8CS2liOwOw6wGMObCw6Cuh/KNn4HgiuIjvst3JJw Gf1AOoIE71+eWkqJn8gXAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAIdwRTLMzwq0 4biZJlpLqE5hOTUGDsWkpHgpQLgaLFNaltZIe2e2H14O+FtbI9xeaVzXzXjAIMyX vAmstyqZCOAvE+alo85E/KZEn4/Cwq8yhT70HU32wz6O1gEsn4LN1Frrs8DB+OwW kcsv3aR6ETr81zRJB3D7LAJlD4ZBJX//HTGlHYZ28t4gyUAf8+yRytRtt0SxfI+b 3h9LmKF0QllScEHR2GclvQvqZe+Er4Z796AFsQaf6ZOVornrQ8l23sHKRLJxeb2S 3SehH9ldqcKv69CXLCQS3wisNNXAHhrPSchL1tklaq3TgKaews153/1IM+R2qpk4 oG1mXXB7UP4=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</KeyDescriptor>
<ArtifactResolutionService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://centos.gluu.info:9443/idp/profile/SAML2/SOAP/ArtifactResolution" index="2"/>
<NameIDFormat>urn:mace:shibboleth:1.0:nameIdentifier</NameIDFormat>
<NameIDFormat>
urn:oasis:names:tc:SAML:2.0:nameid-format:transient
</NameIDFormat>
<NameIDFormat>
urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
</NameIDFormat>
<SingleSignOnService Binding="urn:mace:shibboleth:2.0:profiles:AuthnRequest" Location="https://centos.gluu.info/idp/profile/SAML2/Unsolicited/SSO"/>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://centos.gluu.info/idp/profile/SAML2/POST/SSO"/>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="https://centos.gluu.info/idp/profile/SAML2/POST-SimpleSign/SSO"/>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://centos.gluu.info/idp/profile/SAML2/Redirect/SSO"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://centos.gluu.info/idp/profile/SAML2/Redirect/SLO"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://centos.gluu.info/idp/profile/SAML2/POST/SLO"/>
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="https://centos.gluu.info/idp/profile/SAML2/POST-SimpleSign/SLO"/>
<!--

        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://centos.gluu.info:8443/idp/profile/SAML2/SOAP/SLO"/>
        
-->
</IDPSSODescriptor>
<Organization>
<OrganizationName xml:lang="en">gluu</OrganizationName>
<OrganizationDisplayName xml:lang="en">gluu</OrganizationDisplayName>
<OrganizationURL xml:lang="en">https://centos.gluu.info</OrganizationURL>
</Organization>
</EntityDescriptor>
```

**Comment by aliaksander-samuseu** [comment]
I can confirm the issue exists in CentOS7.2. Simply adding TR for my Shibboleth SP which still works perfectly fine with Gluu 2.4.4SP3 using web UI doesn't work at all. Despite the fact the TR is created, passes metadata validation and becomes active, any attempt to use it results in "The application you have accessed is not registered for use with this service" error. In logs it just says:

```
2017-02-08 17:20:06,849 - DEBUG [org.opensaml.saml.metadata.resolver.impl.BasicRoleDescriptorResolver:198] - Metadata document did not contain a descriptor for entity https://sphost-shib.site:8443/shibboleth
2017-02-08 17:20:06,850 - DEBUG [org.opensaml.saml.metadata.resolver.impl.BasicRoleDescriptorResolver:281] - Metadata document did not contain any role descriptors of type {urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor for entity https://sphost-shib.site:8443/shibboleth
2017-02-08 17:20:06,851 - DEBUG [org.opensaml.saml.metadata.resolver.impl.BasicRoleDescriptorResolver:252] - Metadata document does not contain a role of type {urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor supporting protocol urn:oasis:names:tc:SAML:2.0:protocol for entity https://sphost-shib.site:8443/shibboleth
2017-02-08 17:20:06,851 - INFO [org.opensaml.saml.common.binding.impl.SAMLMetadataLookupHandler:128] - Message Handler:  No metadata returned for https://sphost-shib.site:8443/shibboleth in role {urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor with protocol urn:oasis:names:tc:SAML:2.0:protocol
2017-02-08 17:20:06,890 - DEBUG [net.shibboleth.idp.profile.impl.WebFlowMessageHandlerAdaptor:154] - Profile Action WebFlowMessageHandlerAdaptor: Invoking message handler of type 'org.opensaml.saml.common.binding.impl.SAMLAddAttributeConsumingServiceHandler' on INBOUND message context
2017-02-08 17:20:06,905 - DEBUG [net.shibboleth.idp.profile.impl.WebFlowMessageHandlerAdaptor:175] - Profile Action WebFlowMessageHandlerAdaptor: Invoking message handler on message context containing a message of type 'org.opensaml.saml.saml2.core.impl.AuthnRequestImpl'
2017-02-08 17:20:06,906 - DEBUG [org.opensaml.saml.common.binding.impl.SAMLAddAttributeConsumingServiceHandler:110] - Message Handler:  No metadata context found, nothing to do
2017-02-08 17:20:06,910 - DEBUG [net.shibboleth.idp.saml.profile.impl.InitializeRelyingPartyContextFromSAMLPeer:132] - Profile Action InitializeRelyingPartyContextFromSAMLPeer: Attaching RelyingPartyContext based on SAML peer https://sphost-shib.site:8443/shibboleth
2017-02-08 17:20:06,913 - DEBUG [net.shibboleth.idp.relyingparty.impl.DefaultRelyingPartyConfigurationResolver:293] - Resolving relying party configuration
2017-02-08 17:20:06,914 - DEBUG [net.shibboleth.idp.relyingparty.impl.DefaultRelyingPartyConfigurationResolver:299] - Profile request is unverified, returning configuration shibboleth.UnverifiedRelyingParty
2017-02-08 17:20:06,914 - DEBUG [net.shibboleth.idp.profile.impl.SelectRelyingPartyConfiguration:136] - Profile Action SelectRelyingPartyConfiguration: Found relying party configuration shibboleth.UnverifiedRelyingParty for request
2017-02-08 17:20:06,918 - WARN [net.shibboleth.idp.profile.impl.SelectProfileConfiguration:111] - Profile Action SelectProfileConfiguration: Profile http://shibboleth.net/ns/profiles/saml2/sso/browser is not available for relying party configuration shibboleth.UnverifiedRelyingParty
2017-02-08 17:20:06,943 - WARN [org.opensaml.profile.action.impl.LogEvent:76] - An error event occurred while processing the request: InvalidProfileConfiguration
2017-02-08 17:20:06,944 - DEBUG [org.opensaml.saml.common.profile.logic.DefaultLocalErrorPredicate:154] - No SAMLBindingContext or binding URI available, error must be handled locally
```

**Comment by uboznikov** [comment]
@zamilskhan @aliaksander-samuseu Please attach `shibboleth2.xml`.

**Comment by aliaksander-samuseu** [comment]
@uboznikov 

You mean the one from my test SP, right? [Here it is](https://github.com/GluuFederation/oxShibboleth/files/764555/shib-files.tar.gz), together with SP's metadata

**Comment by OneLoveAmaru** [comment]
@uboznikov You don't need to collect everyones configs, just install a fresh copy of 3.0.0, it's broken out of the box.

**Comment by aliaksander-samuseu** [comment]
@nynymike @otataryn 

Per Michael's request I tried to look into it a bit deeper. I'm still can't see any reasons for it. Below is grep for entityid of my SP in conf dir:

```
/opt/shibboleth-idp/metadata/5266820E4BCC47FD000294ECCF2C000696A00B30-sp-metadata.xml:<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="_1b45e8a30cfcf25ab6208fc02d7a88196cb656c4" entityID="https://sphost-shib.site:8443/shibboleth">
/opt/shibboleth-idp/metadata/5266820E4BCC47FD000294ECCF2C000696A00B30-sp-metadata.xml:        <ds:KeyName>https://sphost-shib.site:8443/shibboleth</ds:KeyName>
/opt/shibboleth-idp/conf/attribute-filter.xml:        <PolicyRequirementRule xsi:type="Requester" value="https://sphost-shib.site:8443/shibboleth" />
/opt/shibboleth-idp/conf/relying-party.xml:        <bean parent="RelyingPartyByName" id="5266820E4BCC47FD000294ECCF2C000696A00B30" c:relyingPartyIds="https://sphost-shib.site:8443/shibboleth">
```

Seems like it went into all places it should be at. And here is request my SP sends to Gluu:

```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    AssertionConsumerServiceURL="https://sphost-shib.site:8443/Shibboleth.sso/SAML2/POST"
                    Destination="https://cs7gluu3.host.loc/idp/profile/SAML2/Redirect/SSO"
                    ID="_29ad80011a72c45cdf138943ac6d87c4"
                    IssueInstant="2017-02-09T21:43:50Z"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    Version="2.0"
                    >
    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://sphost-shib.site:8443/shibboleth</saml:Issuer>
    <samlp:NameIDPolicy AllowCreate="1" />
</samlp:AuthnRequest>
```

The entityid in request is the same. I can't see any errors in logs during idp's start up revealing any issues with metadata either. I'm not sure what else to check.

**Comment by aliaksander-samuseu** [comment]
@nynymike @zamilskhan @otataryn 

Just a quick update: I managed to make it to work. Not quite sure what steps are, but it's clearly not working as it should. I believe I first configured a custom Relying parties settings, it still didn't work after that, though I saw configuration in IdP's dir updated and in idp-process.log there were signs it reloaded it from disk. I believe it's after I cleared all cookies for this instance and re-tried the flow it started to work.

**Comment by uboznikov** [comment]
@OneLoveAmaru `shibboleth2.xml` is a crucial part of the config so it should be added to the checking/testing.

**Comment by zamilskhan** [comment]
The error in the idp-process log for the problem is as follows
```
2017-02-14 17:48:34,752 - WARN [net.shibboleth.idp.profile.impl.SelectProfileConfiguration:111] - Profile Action SelectProfileConfiguration: Pro
file http://shibboleth.net/ns/profiles/saml2/sso/browser is not available for relying party configuration shibboleth.UnverifiedRelyingParty
2017-02-14 17:48:34,759 - WARN [org.opensaml.profile.action.impl.LogEvent:76] - An error event occurred while processing the request: InvalidPro
fileConfiguration
```

**Comment by aliaksander-samuseu** [comment]
@uboznikov , please let us know whether you succeed in reproducing this issue and are already working on this, or should we still try to investigate it further.

After I managed to make my previous TR (the one with custom RP config) to work, I removed it. Then I created another one right away, now without the custom RP config - it worked nevertheless. But after I restarted idp service, it stopped to work, and even removing it and creating another one (still without custom RP config) didn't help.

After I managed to add a custom RP config to it again (there is another issue there, for some reason it doesn't add it on first one or two attempts, but in the end it works somehow, with try and error, can't provide steps yet), it worked again. Then I again removed the one with custom RP config, created another without custom RP config - it worked again. Restarted idp - it's again broken.

Please let me know if you need video of this, I'll try to record one.

**Comment by zamilskhan** [comment]
I saw this error when trying to create a TR in 3.0.1 
https://pastebin.com/18EKK2Uw

**Comment by yurem** [comment]
@zamilskhan , @mzico , @aliaksander-samuseu can you give list of steps which I can use to reproduce it? Are there any instructions about SP configuration?

**Comment by zamilskhan** [comment]
I followed the shibboleth sp integration guide from [our docs](https://gluu.org/docs/2.4.4/integration/saml-sp/)

**Comment by aliaksander-samuseu** [comment]
@yurem If you simply configure a regular test SP without custom RP config in it right after installation (let's not restart anything or clear any cookies for now), it will most likely be broken. So no specific steps there, add a SP with a couple of attributes, and you should see it.

**Comment by wkuntz** [comment]
We are also experiencing this issue.  I see that it was closed.  What was the resolution?

**Comment by OneLoveAmaru** [comment]
I'm still waiting for a fix. Why was it closed with no fix?

**Comment by mzico** [comment]
@wkuntz @OneLoveAmaru : We will have new release published on Monday or Tuesday; it has such fix.

**Comment by yurem** [comment]
We fixed this file: https://github.com/GluuFederation/community-edition-setup/commit/258e80ffe285831a3807d57c2f570f5c5ebcf780

**Comment by yurem** [comment]
You can update /opt/shibboleth-idp/conf/services.properties in your environment to allow IDP to check if it should reload metdata.

**Comment by wkuntz** [comment]
I updated that file, stopped and started Gluu and still received the same error.  I then deleted the TR, and recreated it via the GUI.  I still get the same error.  

If you let me know what logs you need, I will be happy to help troubleshoot.

Bill

**Comment by yurem** [comment]
Did you wait 1 minute after validation success in oxTrust?

**Comment by wkuntz** [comment]
Yes.  I has been about 15 minutes, and still get the same error:

Web Login Service - Unsupported Request
The application you have accessed is not registered for use with this service.

**Comment by aliaksander-samuseu** [comment]
@wkuntz @OneLoveAmaru 

You can try to add "Custom RP config" to the TR you create. When setting this custom RP config try to use configuration provided in [this example](https://gluu.org/docs/admin-guide/saml/#add-trust-relationship). Then you'll need to wait until IdP reloads config, or restart it with `service idp restart`. If it won't resolve the issue, you may try to fetch the latest oxtrust.war from [here](https://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0/oxtrust-server-3.0.0.war) and use [this guide](https://gluu.org/docs/upgrade/update-war/) to upgrade it in the container (rename it to identity.war and make sure it can be read by `jetty` user). Note that even in this updated war you still must add Custom RP config for it to work, even if you don't actually need it (with default settings it won't change flow much anyway).

**Comment by aliaksander-samuseu** [comment]
@wkuntz @OneLoveAmaru 

CentOS 6 and Ubuntu 14 packages have just been rebuilt, so instead of update identity.war manually you could install from them a new instance, if it's an option.

**Comment by wkuntz** [comment]
Is the upgrade from 3.0.0 just a yum update?

Bill

**Comment by wkuntz** [comment]
After a reboot, this is working.  Perhaps everything did not get restarted properly after I made the change previously.

**Comment by yurem** [comment]
In 3.0.1 we added this update to enable automatic metadata reload:
https://github.com/GluuFederation/community-edition-setup/commit/258e80ffe285831a3807d57c2f570f5c5ebcf780

You can manually update: /opt/shibboleth-idp/conf/services.properties
And run: service idp restart

After that IDP should automatically reload metadata after addin/changing TR.

**Comment by OneLoveAmaru** [comment]
I just installed a fresh instance of 3.0.1 on CentOS 7 and this doesn't
appear to be fixed.

I waited many minutes to make sure the metadata reloaded but no go.

I even tried restarting Gluu, waited 10 minutes but still getting "The
application you have accessed is not registered for use with this service."

idp.process.log shows:

2017-03-02 16:16:03,844 - INFO
[org.opensaml.saml.common.binding.impl.SAMLMetadataLookupHandler:128] -
Message Handler:  No metadata returned for
https://sp.testshib.org/shibboleth-sp in role
{urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor with protocol
urn:oasis:names:tc:SAML:2.0:protocol
2017-03-02 16:16:03,849 - WARN
[net.shibboleth.idp.profile.impl.SelectProfileConfiguration:111] - Profile
Action SelectProfileConfiguration: Profile
http://shibboleth.net/ns/profiles/saml2/sso/browser is not available for
relying party configuration shibboleth.UnverifiedRelyingParty
2017-03-02 16:16:03,853 - WARN
[org.opensaml.profile.action.impl.LogEvent:76] - An error event occurred
while processing the request: InvalidProfileConfiguration



~Matt

**Comment by willow9886** [comment]
Matt, Can you please move this over to http://support.gluu.org ?

It will be easier for our team to troubleshoot the issue there. Thanks.
